spring.application.name=InsecWeb
server.port=8080
server.ssl.enabled=true
server.ssl.protocol=TLSv1
server.ssl.enabled-protocols=TLSv1,TLSv1.1,TLSv1.2
logging.level.root=INFO
spring.datasource.url=jdbc:postgresql://localhost:5432/appdb
spring.datasource.username=appuser
spring.datasource.password=S3cr3tP@ssw0rd!
